### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by ghost** [dnauck/Portable.Licensing#30]
System.ArgumentException: illegal object in GetInstance: DerOctetString

   at Org.BouncyCastle.Asn1.DerBitString.GetInstance(Object obj)
   at Org.BouncyCastle.Asn1.X509.SubjectPublicKeyInfo..ctor(Asn1Sequence seq)
   at Org.BouncyCastle.Asn1.X509.SubjectPublicKeyInfo.GetInstance(Object obj)
   at Org.BouncyCastle.Security.PublicKeyFactory.CreateKey(Byte[] keyInfoData)
   at Portable.Licensing.Security.Cryptography.KeyFactory.FromPublicKeyString(String publicKey)
   at Portable.Licensing.License.VerifySignature(String publicKey)
   at Portable.Licensing.Validation.LicenseValidationExtensions.<>c__DisplayClassd.<Signature>b__c(License license)
   at Portable.Licensing.Validation.ValidationChainBuilder.<AssertValidLicense>d__1.MoveNext()
   at LicenseGen.Program.Main(String[] args) in c:\Users\0xFireball\Programs\C#\ExaPhaser\Licensing\FireCryptEx\KeyGen\LicenseGen\Program.cs:line 39

**Comment by ghost** [comment]
if (validationFailures.Any())
            {
                foreach (var failure in validationFailures.ToList())
                     Console.WriteLine(failure.GetType().Name + ": " + failure.Message + " - " + failure.HowToResolve);
            }

**Comment by ArcherTrister** [comment]
Maybe the public and private keys are confusing.
